/*
 * inter_font.h — Lightweight renderer for tide-clock bitmap fonts.
 *
 * Font files are generated by tools/font_to_c.py from Inter TTF.
 * Glyph bitmaps are packed 4bpp (2 pixels per byte, high nibble first).
 * Alpha values: 0 = fully transparent, 15 = fully opaque.
 *
 * Usage (8-bit grayscale frame buffer, 0 = black, 255 = white):
 *
 *   #include "inter_font.h"
 *   #include "fonts/inter_sb_96.h"
 *
 *   uint8_t buf[960 * 680];
 *   memset(buf, 255, sizeof(buf));          // white background
 *   inter_draw_string(buf, 960, 680,
 *                     40, 200,              // x, baseline_y
 *                     "1 FT 3 IN", &inter_sb_96);
 */

#ifndef INTER_FONT_H
#define INTER_FONT_H

#include <stdint.h>

/* -------------------------------------------------------------------------
 * Data types (populated by font_to_c.py output)
 * ---------------------------------------------------------------------- */

typedef struct {
    char     ch;           /* character this glyph represents              */
    uint8_t  width;        /* bounding box width in pixels                 */
    uint8_t  height;       /* bounding box height in pixels                */
    int8_t   ofs_x;        /* pen-to-bbox-left offset (can be negative)    */
    int8_t   ofs_y;        /* baseline-to-bbox-bottom offset               */
                           /*   positive → bottom above baseline (caps)    */
                           /*   negative → bottom below baseline (descend) */
    uint16_t adv_w;        /* advance width, 26.6 fixed-point pixels       */
                           /*   integer pixels ≈ adv_w / 64               */
    uint32_t data_offset;  /* byte offset into font->bitmaps               */
} InterGlyph;

typedef struct {
    const uint8_t    *bitmaps;     /* packed 4bpp pixel data               */
    const InterGlyph *glyphs;      /* one entry per char in charset        */
    const char       *charset;     /* ordered character list               */
    const int8_t     *kern_table;  /* NxN kern adjustments (pixels), or   */
                                   /* NULL to skip kerning.                */
                                   /* kern_table[i*N+j]: px to add after  */
                                   /* glyph i when followed by glyph j.   */
    uint16_t          num_glyphs;  /* length of glyphs[], charset, kern N */
    uint8_t           line_height; /* full line height in pixels           */
    uint8_t           ascent;      /* distance from baseline to line top   */
} InterFont;

/* -------------------------------------------------------------------------
 * API
 * ---------------------------------------------------------------------- */

/*
 * inter_find_glyph — return the glyph descriptor for a character, or NULL.
 */
const InterGlyph *inter_find_glyph(const InterFont *font, char ch);

/*
 * inter_measure_string — return the pixel width of a string.
 */
int inter_measure_string(const InterFont *font, const char *str);

/*
 * inter_draw_string — render a string into an 8-bit grayscale buffer.
 *
 *   buf        — 1 byte per pixel, row-major, 0=black 255=white
 *   buf_w/h    — buffer dimensions
 *   x          — starting pen x (left edge of first glyph)
 *   baseline_y — y coordinate of the text baseline
 *   str        — null-terminated ASCII string
 *   font       — font to use
 *
 * Returns the x position after the last glyph (useful for concatenation).
 */
int inter_draw_string(uint8_t *buf, int buf_w, int buf_h,
                      int x, int baseline_y,
                      const char *str, const InterFont *font);

/*
 * inter_draw_string_4gray — render into a Waveshare 4-gray frame buffer.
 *
 * The Waveshare 4-gray format packs 4 pixels per byte (2 bits each).
 * Pixel order within a byte: px0 in bits[7:6], px1 in [5:4], etc.
 * Gray levels: 0x00=black, 0x01=dark gray, 0x02=light gray, 0x03=white.
 *
 *   buf        — (width/4) * height bytes
 *   buf_w/h    — frame buffer dimensions in pixels
 *   x          — starting pen x
 *   baseline_y — y coordinate of the text baseline
 *   fg         — foreground gray level (0–3; 0 = black)
 *   str        — null-terminated ASCII string
 *   font       — font to use
 *
 * Returns the x position after the last glyph.
 */
int inter_draw_string_4gray(uint8_t *buf, int buf_w, int buf_h,
                             int x, int baseline_y,
                             uint8_t fg,
                             const char *str, const InterFont *font);

#endif /* INTER_FONT_H */
